apiVersion: v1
kind: Service
metadata:
  name: second-deployment-service
spec:
  selector: 
    my-selector-key1: my-selector-value1
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer